config/routes.rb
Appdev::Application.routes.draw do

  devise_for :users
  root 'main#home'
  get '/about' => 'main#about'
  get '/contact' => 'main#contact'
  get '/review/:id' => 'main#review',as: :review
  post '/addreview' => 'data#addreview',as: :addreview
  get '/add' => 'data#add_form',as: :add 
  post '/insert' => 'data#insert',as: :insert
  get '/show' => 'data#show',as: :show
  get '/edit/:id' => 'data#edit_form',as: :edit
  put '/update' => 'data#update',as: :update
  delete '/delete/:id' => 'data#delete',as: :delete
  get '/manage' => 'data#index',as: :manage
  get '/get_ticker' => 'main#get_ticker'
  

  

  

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :hotel
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :hotels
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_filter :authenticate_user!
  def insert
    hotel = Hotel.new
    hotel.name = params[:name]
    hotel.city = params[:city]
    hotel.description = params[:description]
    hotel.rating = params[:rating]
    hotel.user_id = current_user.id
    if hotel.save
      flash[:notice] = "Saved Successfully"
      redirect_to manage_path and return
    else
      flash[:error] = "The Data you have entered needs to be checked"
      redirect_to manage_path and return
    end
  end

  def update
    hotel = current_user.hotels.find params[:id]
    hotel.name = params[:name]
    hotel.city = params[:city]
    hotel.description = params[:description]
    hotel.rating = params[:rating] 

    if hotel.save
      flash[:notice] = "Saved Successfully"
      redirect_to edit_url(params[:id]) and return
    else
      flash[:error] = "The Data you have entered needs to be checked"
      redirect_to edit_url(params[:id]) and return
      end
  end

  def delete
    hotel = current_user.hotels.find params[:id]
    if hotel.delete
      flash[:notice] = "Deleted #{hotel.name}" 
      redirect_to manage_path and return
    else
      flash[:error] = "Error"
      redirect_to manage_path and return
    end
  end

  def show
    @hotels = current_user.hotels
  end

  def add_form
  end

  def edit_form
    @hotel = current_user.hotels.find params[:id]
  end

  def addreview
    review = Review.new
    review.content = params[:content]
    review.hotel_id = params[:id]
    review.user_id = current_user.id
    if review.save
      flash[:notice] = "Saved Successfully"
      redirect_to review_url(params[:id]) and return
    else
      flash[:error] = "The Data you have entered needs to be checked"
      redirect_to review_url(params[:id]) and return
      end
  end

  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  	@hotels = Hotel.all
  end

  def about
  end

  def contact
  end

  def review
  	@hotel = Hotel.find params[:id]
  end

  def get_ticker
    news = Ticker.all
    render :json => news
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/data/add_form.html.erb
<div>
	<%= form_tag(insert_path, method: :post) do %>
	 <input name = "name" type = "text" class = "form-control" placeholder = "Hotel Name" required/>
	 <input name = "city" type = "text" class = "form-control" placeholder = "City" required/>
	 <textarea name = "description" class = "form-control" placeholder = "Hotel Description" required></textarea>
	 <input name = "rating" class = "form-control" type="number" min = "1" max = "5" placeholder = "Rating" required/>
	 <input type="submit" class="btn btn-primary"/>
	<% end %>
</div>

app/views/data/edit_form.html.erb
<div>
	<div id="error-note"></div>
	<%= form_tag(update_path, method: :put) do %>
	<input name = "id" type = "hidden" value="<%= @hotel.id %>"/>
	 <input name = "name" id="name" type = "text" class = "form-control" placeholder = "Hotel Name" value="<%= @hotel.name %>" required/>
	 <input name = "city" id="city" type = "text" class = "form-control" placeholder = "City" value="<%= @hotel.city %>" required/>
	 <textarea name = "description" id="description" class = "form-control" placeholder = "Hotel Description" required><%= @hotel.name %></textarea>
	 <input name = "rating" id="rating" class = "form-control" type="number" min = "1" max = "5" placeholder = "Rating" value="<%= @hotel.rating %>" required/>
	 <input type="submit" id="submitbutton" class="btn btn-primary"/>
	<% end %>
</div>

app/views/data/index.html.erb
<div class="container data"></div>

app/views/data/show.html.erb
<div class="data container">
	<div class="col-lg-12">
		<% @hotels.each do |hotel| %>
		<h4><%= hotel.name %></h4>
		<h4><%= hotel.city %></h4>
		<h4><%= hotel.description %></h4>
		<h4><%= hotel.rating %></h4>	
			<div>
				<%= link_to 'Edit',edit_url(hotel.id), :class => 'btn btn-info' %>
				<%= link_to 'Delete',delete_url(hotel.id), :class => 'btn btn-info', method: :delete %>
			</div>
		<hr>
		<% end %>
	</div>
	
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success alert-dismissable">
  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  		<%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="alert alert-warning alert-dismissable">
  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  		<%= flash[:error]%>
	</div>

<% end %>

<% if flash[:alert] %>
	<div class="alert alert-warning alert-dismissable">
  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  		<%= flash[:alert]%>
	</div>

<% end %>

app/views/layouts/_navbar.html.erb
<div class="header">
        <ul class="nav nav-pills pull-right">
           <li class="active"><%= link_to 'Home',root_path %></li>
            <li><%= link_to 'About',about_path %></li>
            <li><%= link_to 'Contact',contact_path %></li>
            <li><%= link_to 'Add Hotel',add_path %></li>
            <li><%= link_to 'Manage', show_path %></li>

            <li><!-- Split button -->
				<div class="btn-group">
					
				  <button type="button" class="btn btn-primary">Account</button>
				  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				    <span class="caret"></span>
				    <span class="sr-only">Toggle Dropdown</span>
				  </button>
				  <ul class="dropdown-menu" role="menu">

				    <!-- User Has Logged in -->
				    <% if user_signed_in? %>

				    <li><a href="#"><%= current_user.name %></a></li>
				    <li><a href="#"><%= current_user.email %></a></li>
				    <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>
				    
				    <% else %>
				    <li><%= link_to "Sign In",new_user_session_path %></li>
				    <li><%= link_to "Register",new_user_registration_path %></li>
				    <% end %>
				  
				  </ul>
				</div>
			</li>
        </ul>
        <h3 class="text-muted">Hotel Review</h3>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appdev</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    controller_name, media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body ng-app='hotel'>
	<div class = "container">
		<%= render 'layouts/navbar' %>
		<%= render 'layouts/flash' %>
		<%= yield %>
		<hr>
		<div class="footer">
        	<p>&copy; Hotel Management 2013-14</p>
        </div>
	</div>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag controller_name, "data-turbolinks-track" => true %>
</body>

</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/contact.html.erb
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

app/views/main/home.html.erb
    
<div class = "container" ng-controller = "homeController" >
    <div class="container data">
 
        <%= image_tag('Indian_Food-4.jpg', :alt =>'I am Sorry', :class =>"food") %>
    

      <div class="row marketing">
        <div class="col-lg-6">
        <% @hotels.each do |hotel| %>
          <h4><%= link_to hotel.name,review_url(hotel.id) %></h4>
          <p><%= hotel.description %></p>
          <p><%= hotel.user.name %></p>
          <p><%= hotel.user.email %></p>

        <% end %>
        </div>
          <div class="col-lg-6 well" >
            <ul>
            <li ng-repeat="a in myname">{{a.name}}</li>
            <li ng-repeat="a in myname">{{a.age}}</li>
          </ul>
          </div>        
      </div>

	{{1+2}}
</div>
</div>

app/views/main/review.html.erb
<div class="container data">
	<h1><%= @hotel.name %></h1>
	<p><%=  @hotel.description %></p>
    <p><%=  @hotel.user.name %></p>
    <hr>
    <h1>User Reviews</h1>
    <% @hotel.reviews.each do |review| %>
    <p><%= review.content  %></p>
    <p><%= review.user.name %></p>
    <hr>
    <% end %>

    <%= form_tag(addreview_path, method: :post) do %>
        <input name = "id" type = "hidden" value="<%= @hotel.id %>"/>
    	<textarea name = "content" class = "form-control" placeholder = "Hotel review" required></textarea>
    	<input type="submit" class="btn btn-primary"/>
    <% end %>

</div>